allowed_families:
  - GBM
  - XGB
  - CAT
  - RF
  - XT
  - NN_TORCH
  - KNN
  - LR

presets:
  fast: "medium_quality"
  balanced: "good_quality"
  thorough: "best_quality"

default_time_limit: 120
default_presets: "medium_quality"
