"""
Preprocessing plan produced by PreprocessingAgent (Phase 4b) or stub (Phase 4a).

Origin  : PreprocessingAgent (not yet built) or CampaignOrchestrator stub
Consumed: PreprocessingExecutor (src/execution/preprocessing_runner.py)
"""
from __future__ import annotations
from typing import List, Literal, Optional
from pydantic import BaseModel


class PreprocessingPlan(BaseModel):
    """
    Describes how to transform raw data before AutoGluon sees it.

    Phase 4a: strategy="identity" — data passed through unchanged.
    Phase 4b: strategy="generated" — code contains a preprocess(df, target_col) function
              generated by PreprocessingAgent and validated by ValidationHarness.
    """
    strategy: Literal["identity", "generated"] = "identity"
    code: Optional[str] = None         # Python function string (Phase 4b only)
    rationale: str = ""                # agent's reasoning
    transformations: List[str] = []    # human-readable list of what the code does
