"""
Preprocessing models for Phase 4b.

PreprocessingPlan  — describes how to transform raw data (identity or generated code).
PreprocessingEntry — long-term memory record for one successful preprocessing session,
                     persisted to preprocessing_bank.jsonl by PreprocessingStore.
"""
from __future__ import annotations
from datetime import datetime
from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class PreprocessingPlan(BaseModel):
    """
    Describes how to transform raw data before AutoGluon sees it.

    Phase 4a: strategy="identity" — data passed through unchanged.
    Phase 4b: strategy="generated" — code contains a preprocess(df) function
              generated by PreprocessingAgent and validated by ValidationHarness.

    validation_passed: True if ValidationHarness accepted the generated code.
    turns_used: number of ReAct turns consumed by PreprocessingAgent.
    """
    strategy: Literal["identity", "generated"] = "identity"
    code: Optional[str] = None         # Python function string (Phase 4b only)
    rationale: str = ""                # agent's reasoning
    transformations: List[str] = []    # human-readable list of what the code does
    validation_passed: bool = False    # True if ValidationHarness accepted the code
    turns_used: int = 0                # ReAct turns consumed (0 = agent not called)


class PreprocessingEntry(BaseModel):
    """
    Long-term memory record for one successful preprocessing session.

    Created by: PreprocessingStore.add() after a PreprocessingAgent run.
    Stored in: preprocessing_bank.jsonl (global experiments/ directory).
    Read by: PreprocessingStore.get_similar(), passed to PreprocessingAgent
             as similar_cases so it can reuse effective past transformations.

    transformation_summary: human-readable description used by the agent
                            as inspiration in the initial user message.
    embedding: reserved for EmbeddingRetriever (Step 6) — None until populated.
    """
    entry_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    task_type: str                        # "binary", "multiclass", "regression"
    dataset_name: str                     # e.g. "titanic", "house_prices"
    transformation_summary: str           # human-readable description for agent context
    code: str                             # the validated preprocess(df) function
    metric_delta: float = 0.0             # metric improvement from baseline (0 = unknown)
    embedding: Optional[List[float]] = None  # populated by EmbeddingRetriever (Step 6)
